# Form implementation generated from reading ui file './ui/audio_review_label.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_audio_review_label(object):
    def setupUi(self, audio_review_label):
        audio_review_label.setObjectName("audio_review_label")
        audio_review_label.resize(400, 200)
        audio_review_label.setStyleSheet("")
        self.audio_play_button = QtWidgets.QPushButton(parent=audio_review_label)
        self.audio_play_button.setGeometry(QtCore.QRect(130, 85, 30, 30))
        self.audio_play_button.setStyleSheet("background-color: grey;")
        self.audio_play_button.setText("")
        self.audio_play_button.setIconSize(QtCore.QSize(30, 30))
        self.audio_play_button.setObjectName("audio_play_button")
        self.audio_stop_button = QtWidgets.QPushButton(parent=audio_review_label)
        self.audio_stop_button.setGeometry(QtCore.QRect(240, 85, 30, 30))
        self.audio_stop_button.setStyleSheet("background-color: grey;")
        self.audio_stop_button.setText("")
        self.audio_stop_button.setIconSize(QtCore.QSize(30, 30))
        self.audio_stop_button.setObjectName("audio_stop_button")
        self.audio_pause_button = QtWidgets.QPushButton(parent=audio_review_label)
        self.audio_pause_button.setGeometry(QtCore.QRect(185, 85, 30, 30))
        self.audio_pause_button.setStyleSheet("background-color: grey;")
        self.audio_pause_button.setText("")
        self.audio_pause_button.setIconSize(QtCore.QSize(30, 30))
        self.audio_pause_button.setObjectName("audio_pause_button")

        self.retranslateUi(audio_review_label)
        QtCore.QMetaObject.connectSlotsByName(audio_review_label)

    def retranslateUi(self, audio_review_label):
        _translate = QtCore.QCoreApplication.translate
        audio_review_label.setWindowTitle(_translate("audio_review_label", "Form"))
