# Form implementation generated from reading ui file './ui/review_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_review_widget(object):
    def setupUi(self, review_widget):
        review_widget.setObjectName("review_widget")
        review_widget.resize(980, 720)
        self.image_review_label = QtWidgets.QLabel(parent=review_widget)
        self.image_review_label.setGeometry(QtCore.QRect(0, 0, 980, 720))
        self.image_review_label.setText("")
        self.image_review_label.setScaledContents(True)
        self.image_review_label.setObjectName("image_review_label")

        self.retranslateUi(review_widget)
        QtCore.QMetaObject.connectSlotsByName(review_widget)

    def retranslateUi(self, review_widget):
        _translate = QtCore.QCoreApplication.translate
        review_widget.setWindowTitle(_translate("review_widget", "Form"))
